# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "邾的技术专栏"
brief-intro: "System Research"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhu13818202655.github.io/" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #gaohaoyang126
facebook_username: #gaohaoyang.water
github_username:  zhu13818202655
email: 18810151125@163.com
weibo_username: 18810151125
zhihu_username: 18810151125


description_footer: 来自邾的个人专栏！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: xyao #hygblog
# disqus_shortname: #gaohaoyang
# using Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 9216da7a06a8d7e6d5f2                           #生成的clientID
  clientSecret: 5787c80810a86176436e9364f17b2036f1ab144e    #生成的clientSecret
  repo: zhu13818202655.github.io    #仓库名称
  owner: zhu13818202655    #github用户名
  admin: zhu13818202655
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
#hm.src = "//hm.baidu.com/hm.js?527131ceb8f81e894cdc98a138a108c3";
# xxxxx字符串
baidu_tongji_id: 527131ceb8f81e894cdc98a138a108c3
google_analytics_id: UA-134193738-1 # google 分析追踪id
ga_domain: auto

friends: [
    {
        title: "Linkedin - Xin YAO",
        href: "https://www.linkedin.com/in/%E4%BF%A1-%E5%A7%9A-947492167/"
    }
]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"
#
#sitemap
url: "https://zhu13818202655.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap


# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001
